### ISSUE TITLE
Would be very useful as a decorator

### ISSUE THREAD

**Issue by MeLight** [mrf345/flask_minify#17]
I have an app which builds js assets at runtime. It would be very useful if I could apply it to a single endpoint that generates those, rather than the whole app and then try and regex all the other endpoints of the app.

Either a decorator to apply to an endpoint or a positive list vs only a negative one would be great.

**Comment by mrf345** [comment]
I'm about to merge a PR https://github.com/mrf345/flask_minify/pull/18 that adds a decorator and a flag `passive=False` option to disable positive minification.

**Comment by MeLight** [comment]
That's awesome, thanks!

**Comment by mrf345** [comment]
Most welcome!  `pip install -U Flask-Minify`
