### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by ra-esmith** [mrf345/flask_minify#2]
I  tried using flask_minify, got an error ... help.

Thanks,
Evan

Seems so easy to use ... but not sure what the error is about ...

[run.log](https://github.com/mrf345/flask_minify/files/2762074/run.log)

**Comment by mrf345** [comment]
Looks like the `response` is no longer a decode-able bytes type. I think last i checked that issue will happen when initiating `flask-compress` prior to initiating `flask-minify`. try to initiate `flask-minify` first.
