### ISSUE TITLE
Flask Minify does not minify HTML, CSS or JS in my flask code.

### ISSUE THREAD

**Issue by RohitShende** [mrf345/flask_minify#21]
Hi,

I followed the process to install and use flask-minify on PyPi website - [ https://pypi.org/project/Flask-Minify/](url)

It did not minify any of these when I checked by running my app on my local machine.

I am using - Python 3.6.8

**Comment by mrf345** [comment]
Hello,

The tests seems to be passing for Python 3.6 https://travis-ci.org/github/mrf345/flask_minify/jobs/657535452

Could you please attach a code snippet of how you're using it ?
