### ISSUE TITLE
Some whitespace in template literals is wrongly removed

### ISSUE THREAD

**Issue by Scriptim** [mrf345/flask_minify#29]
```python
#!/usr/bin/env python3

from flask import Flask
from flask_minify import minify

app = Flask(__name__)
minify(app=app, js=True)

@app.route('/')
def index():
  return '<script>const x = 42; document.write(`foo ${x} bar`)</script>'
```
This produces the following response on `GET /`:
```js
<script>const x=42;document.write(`foo ${x}bar`)</script>
```
The output is missing a space character after `${x}`. The error occurs only if `x` is enclosed by curly brackets.

**Comment by mrf345** [comment]
Thanks for the example! I'm about to merge a PR https://github.com/mrf345/flask_minify/pull/30 that resolves it.
