### ISSUE TITLE
UnicodeEncodeError on Python 2.7

### ISSUE THREAD

**Issue by luaz** [mrf345/flask_minify#42]
Bump into the following error

```text
File ".../python2.7/site-packages/Flask_Minify-0.27-py2.7.egg/flask_minify/main.py", line 227, in get_minified_or_cached
    key = hashing(content).hexdigest()
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 42768: ordinal not in range(128)
```
I believe the solution should be

```python
key = hashing(content.encode('utf-8')).hexdigest()
```

**Comment by mrf345** [comment]
Nice catch, thanks for the detailed issue! I'm about to merge a PR that resolves it and adds more test coverage to catch it easily in the future https://github.com/mrf345/flask_minify/pull/43

**Comment by mrf345** [comment]
Should be resolved after updating `pip install -U Flask-Minify==0.28`, please let me know if the issue persists.
