### ISSUE TITLE
Static CSS not minifying

### ISSUE THREAD

**Issue by KTibow** [mrf345/flask_minify#46]
I noticed that for some reason, the CSS wasn't minifying. It was auto-added with `app.add_url_rule`. Any reasons, solutions, or stuff I could do to help debug?

**Comment by mrf345** [comment]
Try first to disable the failsafe option `failsafe=False` (it's enabled by default), so you can get an exception. A better approach is to use the Flask app logger to log exceptions even if the failsafe option is enabled, probably I'll add it in a future PR. In this case, we're expecting `lesscpy` package to fail. You can play around with it to figure out what part of your CSS is causing the failure:

https://github.com/mrf345/flask_minify/blob/master/flask_minify/main.py#L7
https://github.com/mrf345/flask_minify/blob/master/flask_minify/main.py#L156-L158

**Comment by KTibow** [comment]
CSS vars don't work. Do you think I could try babel or something?

**Comment by mrf345** [comment]
Probably a babel-polyfill is a good workaround for now. You can open an issue in the [`lesscpy`](https://github.com/lesscpy/lesscpy) repo they might be able to provide a fix for it. It's been a long time since I checked out that codebase, so unfortunately I won't be able to help much there.

**Comment by ElnuDev** [comment]
> CSS vars don't work. Do you think I could try babel or something?

Not working for me either, unfortunately.

**Comment by mrf345** [comment]
Should soon be resolved in 0.33 release with #64
