### ISSUE TITLE
case and pip install

### ISSUE THREAD

**Issue by ra-esmith** [mrf345/flask_minify#55]
Oddly enough I had an issue doing
pip install flask-minify

while
pip install Flask-Minify 

worked

I had thought case should not matter

**Comment by mrf345** [comment]
It's case-insensitive as far as I know (_testing with Ubuntu_):

![image](https://user-images.githubusercontent.com/26286907/120895880-a76e9b00-c627-11eb-9dbe-5917f8302f80.png)
