### ISSUE TITLE
CSS grid-area values are minified into float values

### ISSUE THREAD

**Issue by guillermohs9** [mrf345/flask_minify#59]
Hi! I'm using Flask-Minify 0.32 which works like a charm. I've found an issue with certain CSS values:

`.div2 { grid-area: 2 / 2 / 3 / 4; }`
`.div3 { grid-area: 1 / 2 / 2 / 3; }`

these are minified into

`div2{grid-area:0.08333333333333;}` 

for example, which breaks the grid layout. I've bypassed the routes to work around this, but I thought I'd submit this issue.

Cheers

**Comment by mrf345** [comment]
Thanks! Should soon be resolved in 0.33 release with #64
