### ISSUE TITLE
Is pyyaml a needed requirement?

### ISSUE THREAD

**Issue by tgross35** [mrf345/flask_minify#70]
I might be missing something, but pyyaml is a dependency that I don't see used anywhere. Could it be removed from requirements, just to trim one dependency?

**Comment by mrf345** [comment]
Nice spot, it's no longer needed at some point we had to pin it for Python 3.4 (which is no longer supported)

https://github.com/mrf345/flask_minify/commit/e08e6f4a2c1480bade4915c0ac13d4a305f6709e
https://github.com/pallets/flask/blob/main/requirements/dev.txt#L99
