### ISSUE TITLE
Release .40 breaks application factories

### ISSUE THREAD

**Issue by keanu-thakalath** [mrf345/flask_minify#81]
The refactoring has resulted in applications that use `init_app` to throw `flask_minify.exceptions.MissingApp`, as the `Minify` object only saves `app` in `__init__`, but not `init_app`, and the `self.app` @property method no longer has the `_app_ctx_stack` to fall back to. Fix it by not saving any specific app in `self._app` and always fall back to `Flask.current_app` in the `self.app` @property.

**Comment by mrf345** [comment]
Nice spot @keanu-thakalath, and thanks for the detailed issue, should be resolved now in [0.41](https://github.com/mrf345/flask_minify/releases/tag/0.41)
