### ISSUE TITLE
Line breaks minifying to a space

### ISSUE THREAD

**Issue by safetymonkey** [mrf345/flask_minify#84]
I think this may be the same issue reported in #47, but it was self-closed and I didn't find the author's solution satisfying.

Basically, I'm seeing confusing behavior about how line breaks are minified. For example, below is the content of my Jinja2 HTML template (leading spaces intentionally kept in to reflect how it looks in my code):
```html
    <nav class="navbar bg-primary fixed-top navbar-expand-md">
      <div class="container-fluid">
        <button
          class="navbar-toggler"
          type="button"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="nav-collapse">
```

It got minified to the following, with spaces between the tags:
```html
<nav class="navbar bg-primary fixed-top navbar-expand-md"> <div class="container-fluid"> <button class="navbar-toggler" type="button"> <span class="navbar-toggler-icon"></span> </button> <div class="collapse navbar-collapse" id="nav-collapse">
```

It's not consistent, though. At the top of that same file (my top-level layout template), I have:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="manifest" href="/manifest.json" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="mobile-web-app-capable" content="yes" />
    <meta name="theme-color" content="#2c3e50" />
```
And that correctly minifies to:
```html
<!DOCTYPE html><html lang="en"> <head><link rel="manifest" href="/manifest.json"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="mobile-web-app-capable" content="yes"><meta name="theme-color" content="#2c3e50">
```
Any ideas what's going on? It's not the end of the world but as long as I'm saving bytes, I want to save ALL the bytes. Thanks!

**Comment by safetymonkey** [comment]
After I posted, this I noticed there's a single space between `<html lang="en">` and `<head>` in my clean example above, so now I'm really confused.

**Comment by mrf345** [comment]
It's an option that can be enabled for `htmlmin`, this should it:

```python
from flask_minify.parsers import Html as HtmlParser


class CustomHtmlParser(HtmlParser):
     runtime_options = {**HtmlParser.runtime_options, "remove_empty_space": True}


# initiating the extension
Minify(app=app, parsers={'html': CustomHtmlParser})
```

checkout https://github.com/mrf345/flask_minify#--parsers for more info

**Comment by skiddy784** [comment]
Why isn't that option enabled by default? It seems reasonable to me...

**Comment by mrf345** [comment]
Should be enabled by default in [0.42](https://github.com/mrf345/flask_minify/releases/tag/0.42)
