### ISSUE TITLE
Rendering of Google Recaptcha doesn't work properly after minifying.

### ISSUE THREAD

**Issue by AndysonDK** [mrf345/flask_minify#9]
So I'm using Flask-wtf's recaptcha field

`from flask_wtf import RecaptchaField` 

And then I'm rendering the recaptcha field using Jinja2

`{{ form.recaptcha }}` 

Which renders the following html:

`<script src='https://www.google.com/recaptcha/api.js' async defer></script>`
`<div class="g-recaptcha" data-sitekey="6LernpkUAAAAAANMNwUpf3RKluSCzaZ_ll16zVZ4"></div>`

For some odd reason, my page looks bad, some content is deleted. When I remove the Recaptcha everything works fine and if I don't minify the page where the Recaptcha is being rendered, everything also works fine.

I doubt this is a problem with the Google Recaptcha or Flask-wtf itself. I think this resides in how the HTML is being minified by the htmlmin library that Flask-Minify uses.

Maybe the Recaptcha HTML code is simply not robust enough to be minified or something like that.

For now, I'm just bypassing the route that renders the page with the Recaptcha field in it.

**Comment by mrf345** [comment]
That's strange. `htmlmin` is the least likely to be causing issues as far as I've observed.
I gave reproducing it a shot, but no luck. I'm using [this app example](https://github.com/Rev0kz/Flask-Google)


![test_recaptcha](https://user-images.githubusercontent.com/26286907/68997356-8f69e600-08e0-11ea-912b-1bac30109fd5.gif)

**Comment by AndysonDK** [comment]
Thanks for the response!
I'm currently just sticking to bypassing the route.

You can close this issue.

**Comment by AndysonDK** [comment]
Actually I found out it has to with the minifying of inline js. If I do this: `minify(app=app, js=False)` it works.

But if I let flask-minify minify the js, it somehow messes up how Recaptcha and google Adsense code works.
It breaks everything, it even removes all of the javaScript sources I have at the end of the body tag.
But if I remove the Google scripts it works perfectly, very weird.

Google Recaptcha html code:

<script src='https://www.google.com/recaptcha/api.js' async defer></script>
<div class="g-recaptcha" data-sitekey="6LcTn5kUAAAAAJ5dBqCcFmfBq4yHkHm8zxjTezZF"></div>


Google Adsense html code:

<script data-ad-client="ca-pub-1173400155815158" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

**Comment by mrf345** [comment]
Well that's very strange. Since these are empty `script` tags so nothing will be passed to the javscript minifier. I tried to reproduced it locally with the tags you've attached, but no luck.

My guess at this point that there's an essential inline `script` that gets added and `jsmin` is failing to minify. Did you try `minify(app=app, js=True, fail_safe=False)` does it raise an exception on that endpoint ?

**Comment by AndysonDK** [comment]
Okay, so I've tried to do `minify(app=app, js=True, fail_safe=False)`

But no errors appear in the console.
Dynamically added scripts might be the issue as you state.

Don't have the energy to find a proper solution anymore sadly.
I'm resorting to not minify inline js at all for now.
