### ISSUE TITLE
Deprecationwarnings

### ISSUE THREAD

**Issue by Tentoxa** [mrf345/flask_minify#95]
In parser.py in line 95 please migrate from "html-keep-conditional-comments" to the new version of it. If not my console will get spammed

![image](https://github.com/mrf345/flask_minify/assets/53821604/4336b37d-3323-441b-aa96-e854192b3078)

**Comment by Tentoxa** [comment]
Oh just saw you can dynamicly modify this.

**Comment by mrf345** [comment]
Nice catch, glad you've found a workaround. I reopened the issue, because I think we should fix this in future versions.
Currently blocked by https://github.com/tdewolff/minify/pull/712

**Comment by Tentoxa** [comment]
> Nice catch, glad you've found a workaround. I reopened the issue, because I think we should fix this in future versions.
> 
> Currently blocked by https://github.com/tdewolff/minify/pull/712

My workaround apparently didn't even work so thanks for fixing this officially!
