### ISSUE TITLE
Exception is raised with default settings if go dependency isn't installed

### ISSUE THREAD

**Issue by Levtastic** [mrf345/flask_minify#97]
The description for the `go` option states
> prefer go minifier, if optional go dependency is installed (default: `True`)

This suggests that if the go dependency is not installed, this option will do nothing. Instead, leaving this option as True causes the parsers to raise an exception from here: https://github.com/mrf345/flask_minify/blob/b7ce727e1f1b681dd71c209b4919d2175cdd4ac7/flask_minify/parsers.py#L134-L142

If a user has a development environment that does not have the extension installed (for example, developing on windows) but still wishes to use the go extension in production, they must explicitly toggle this option based on the code environment, which isn't ideal.

Instead it would be nice if this option was ignored if the go dependency isn't found, as its description suggests it is.

In case it helps anyone else, my current workaround is:
```py
from flask_minify import Minify, parsers
Minify(app, go=bool(parsers.minify_go))
```
But if it suits your deploy process, you could also do the much simpler:
```py
Minify(app, go=not app.debug)
```

**Comment by mrf345** [comment]
Nice catch, and thanks for the thorough description. Should be resolved in `0.48`
I've added a few tests to cover this scenario https://github.com/mrf345/flask_minify/pull/98/commits/d1007734329a6970d5e059153ec6dfb89ce4c528
